name = "lion-panel"
type = "javascript"
account_id = "اینجا-اکانت-ID-کلودفلر-رو-می‌ذاری"
workers_dev = true
compatibility_date = "2024-06-01"

kv_namespaces = [
  { binding = "LION_PANEL_NAMESPACE", id = "اینجا-ID-نام‌اسپیس-KV" }
]
